spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQBymMS8XnVH273LOCnUKs6wZ3O2ARMcIroMVsGGYHiW2TkUnN1IvnzFDu5wmrDbjNYO1h8O2A+HnpWtPK9mqU9A3ojiHDI78a+rrZ0kPxgfmZtcPTZn862ag63T2l0eEocYDyGaHD+CaWAjz4F4jh6GOSu5bP1+7H+Ke4bJy9QcKzGOMJqm1iOpCp5QjcJfAGvl6Aoi6Fk8TxwLyI3mZv6c0oyYVPYGW5WxuvF5zT4/S9KgpdTUb9TrnEOETWr53JrBktg3FcHL01WqmewKU4pXtl4vdCD954Y/kJzN681Z/bFGx+beNpVsl883/W5XyzDNtNFPohz4H2FBVKGoLYkXYC873AmlZMSWPEZ04FBHCQHGkSYYHMhZFeAIbySXO50='
  
token:
  expiration_time: 8640000000  
  secret: my_token_native_changed2_default

gateway:
  ip: 192.168.0.8

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: User's orders is empty. 